---

- job:
    name: tox-molecule-buster
    parent: tox-molecule
    vars:
      tox_envlist: molecule-buster

- job:
    name: tox-molecule-bookworm
    parent: tox-molecule
    vars:
      tox_envlist: molecule-bookworm

- job:
    name: tox-molecule-jammy
    parent: tox-molecule
    vars:
      tox_envlist: molecule-jammy

- project:
    check:
      jobs:
        - tox-linters
        - tox-molecule-buster
        - tox-molecule-bookworm
        - tox-molecule-jammy
    gate:
      jobs:
        - tox-linters
        - tox-molecule-buster
        - tox-molecule-bookworm
        - tox-molecule-jammy
