---

- nodeset:
    name: debian-bookworm-2-node
    nodes:
      - name: primary
        label: debian-bookworm
      - name: secondary
        label: debian-bookworm
    groups:
      - name: switch
        nodes:
          - primary
      - name: peers
        nodes:
          - primary
          - secondary

- job:
    name: ffrouting-deploy
    parent: base
    run: tests/test.yml
    nodeset: debian-bookworm-2-node

- job:
    name: tox-molecule-buster
    parent: tox-molecule
    vars:
      tox_envlist: molecule-buster

- job:
    name: tox-molecule-bookworm
    parent: tox-molecule
    vars:
      tox_envlist: molecule-bookworm

- job:
    name: tox-molecule-jammy
    parent: tox-molecule
    vars:
      tox_envlist: molecule-jammy

- job:
    name: tox-molecule-stream9
    parent: tox-molecule
    vars:
      tox_envlist: molecule-stream9

- project:
    check:
      jobs:
        - ffrouting-deploy
        - tox-linters
        - tox-molecule-buster
        - tox-molecule-bookworm
        - tox-molecule-jammy
        - tox-molecule-stream9
    gate:
      jobs:
        - ffrouting-deploy
        - tox-linters
        - tox-molecule-buster
        - tox-molecule-bookworm
        - tox-molecule-jammy
        - tox-molecule-stream9
