- job:
    name: ffrouting-deploy
    parent: base
    run: tests/test.yml
    nodeset: debian-buster

- project:
    check:
      jobs:
        - ffrouting-deploy
        - tox-linters
    gate:
      jobs:
        - ffrouting-deploy
        - tox-linters
